#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  II III IV V VI VII

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false
bspc config focus_follows_pointer true

bspc config focused_border_color "#BD93F9"
bspc config normal_border_color "#282A36"
bspc config active_border_color "#8BE9FD"
bspc config presel_feedback_color "#50FA7B"

bspc rule -a Gimp desktop='^1' state=floating follow=on
bspc rule -a Web desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a zoom state=floating center=on follow=on border=off
bspc rule --add Pavucontrol state=floating 


# Audio
XF86AudioRaiseVoume
    amixer set Master 5%+


dunst &
feh --bg-scale ~/Pictures/Seattle.jpg &
xset led 3 &
xsetroot -cursor_name left_ptr
sxhkd &
~/.config/polybar/launch.sh &

