#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &



if [[ $(xrandr -q |grep 'HDMI-1 connected') ]]; then
	#xrandr --output HDMI-1 --primary --mode 3840x2160 --rotate normal --left-of eDP-1 --output eDP-1 --mode 1920x1080 --rotate normal
	~/Documents/desktry.sh
else
	~/Documents/laptop.sh
fi

bspc monitor eDP-1 -d 1 2 3 4 5  
#startup
bspc monitor HDMI-1 -d 6 7 8 9 10




#bspc config border_width         2
#bspc config window_gap           8

#bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true
#bspc config single_monocle       false
#bspc config focus_follows_pointer true

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner



bspc config focused_border_color "#BD93F9"
bspc config normal_border_color "#282A36"
bspc config active_border_color "#8BE9FD"
bspc config presel_feedback_color "#50FA7B"

bspc rule -a Gimp desktop='^1' state=floating follow=on
bspc rule -a Web desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a zoom state=floating center=on follow=on border=off
bspc rule --add Pavucontrol state=floating 

dunst &
feh --bg-scale ~/.config/wallpaper/Seattle.jpg &
#xset led 3 &
xset led on & 
xsetroot -cursor_name left_ptr
~/.config/polybar/launch.sh &

